"""
report_generator.py — CostBeat Bot branded PDF
==============================================
Renders the cost-beat analysis and fee proposal as a Camelot-branded PDF, using
the same visual system as `report_bot` — dark navy #1A2645 bands, Camelot gold
#C9A84C accents, Helvetica, and a "Generated by Camelot OS · CostBeat Bot"
footer.

Sections, in order:
  1. Header — property, address, unit count, date
  2. Cost-beat table — Line Item | Their Budget | Camelot Comparable Evidence |
     Camelot Target (Est.) | Est. Annual Savings | % | How We Get There
  3. Totals and savings as a percentage of total budget
  4. Not-addressed disclosure
  5. Fee proposal — both options side by side, recommended one highlighted
  6. Follow-up / next steps checklist
  7. Legend and caveat footer

Copy is evidence-led and plain: figures are stated once, every claim is tied to a
named comparable or a named action, and nothing is described as an opportunity.

Author: Camelot OS
"""

from __future__ import annotations

import io
import logging
import os
from datetime import date
from typing import Any, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from analyzer import AT_MARKET_TEXT, CostBeatAnalysis
from config_loader import load_config
from fee_engine import ONE_TIME, FeeProposal

logger = logging.getLogger("costbeat_bot.report_generator")

# ── Brand palette (matches report_bot/investor_update.py) ──────────────────
GOLD = colors.HexColor("#C9A84C")
NAVY = colors.HexColor("#1A2645")
LIGHT_GOLD = colors.HexColor("#F5EDD6")
LIGHT_GREY = colors.HexColor("#F5F5F5")
MID_GREY = colors.HexColor("#CCCCCC")
DARK_GREY = colors.HexColor("#555555")
GREEN = colors.HexColor("#2E7D32")
WHITE = colors.white

CAVEAT = (
    "Targets are good-faith estimates, not quotes; final numbers follow vendor "
    "bids and records review. Comparable costs are drawn from Camelot's own "
    "managed portfolio as reported in the monthly management reports for the "
    "periods cited. Lines shown at 0% are already at market and no change is "
    "recommended. Fire and life-safety, elevator safety, and statutory scope are "
    "never reduced — those lines may only be rebid at identical scope or audited "
    "for billing accuracy."
)


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

def _styles() -> dict[str, ParagraphStyle]:
    return {
        "title": ParagraphStyle("cbTitle", fontName="Helvetica-Bold", fontSize=17,
                                textColor=WHITE, alignment=TA_CENTER, spaceAfter=3),
        "subtitle": ParagraphStyle("cbSubtitle", fontName="Helvetica", fontSize=10,
                                   textColor=LIGHT_GOLD, alignment=TA_CENTER),
        "section": ParagraphStyle("cbSection", fontName="Helvetica-Bold", fontSize=12,
                                  textColor=NAVY, spaceBefore=12, spaceAfter=4),
        "body": ParagraphStyle("cbBody", fontName="Helvetica", fontSize=9,
                               textColor=colors.black, leading=13, spaceAfter=5),
        "th": ParagraphStyle("cbTh", fontName="Helvetica-Bold", fontSize=8, textColor=WHITE),
        "th_r": ParagraphStyle("cbThR", fontName="Helvetica-Bold", fontSize=8,
                               textColor=WHITE, alignment=TA_RIGHT),
        "td": ParagraphStyle("cbTd", fontName="Helvetica", fontSize=7.5, leading=9.5),
        "td_b": ParagraphStyle("cbTdB", fontName="Helvetica-Bold", fontSize=7.5, leading=9.5),
        "td_r": ParagraphStyle("cbTdR", fontName="Helvetica", fontSize=7.5,
                               leading=9.5, alignment=TA_RIGHT),
        "td_rb": ParagraphStyle("cbTdRB", fontName="Helvetica-Bold", fontSize=7.5,
                                leading=9.5, alignment=TA_RIGHT),
        "opt_head": ParagraphStyle("cbOptHead", fontName="Helvetica-Bold", fontSize=10,
                                   textColor=NAVY, spaceAfter=4),
        "opt_body": ParagraphStyle("cbOptBody", fontName="Helvetica", fontSize=8,
                                   leading=11.5, spaceAfter=3),
        "check": ParagraphStyle("cbCheck", fontName="Helvetica", fontSize=8.5,
                                leading=13, leftIndent=10, spaceAfter=2),
        "caveat": ParagraphStyle("cbCaveat", fontName="Helvetica", fontSize=6.5,
                                 textColor=DARK_GREY, leading=9, alignment=TA_LEFT),
    }


def _footer(canvas: Any, doc: Any) -> None:
    """Gold rule plus the Camelot OS attribution line on every page."""
    canvas.saveState()
    width, _ = doc.pagesize
    y = 0.45 * inch
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(1)
    canvas.line(0.5 * inch, y + 12, width - 0.5 * inch, y + 12)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.grey)
    canvas.drawString(
        0.5 * inch, y,
        f"Generated by Camelot OS · CostBeat Bot | {date.today().strftime('%B %d, %Y')}",
    )
    canvas.drawRightString(width - 0.5 * inch, y, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _header_band(analysis: CostBeatAnalysis, st: dict) -> Table:
    units = f"{analysis.unit_count} units" if analysis.unit_count else "unit count not supplied"
    detail = " · ".join(p for p in (analysis.address, units, analysis.building_type, analysis.market) if p)

    band = Table(
        [
            [Paragraph("CAMELOT PROPERTY MANAGEMENT SERVICES CORP", st["subtitle"])],
            [Paragraph(analysis.property_name.upper(), st["title"])],
            [Paragraph(detail, st["subtitle"])],
            [Paragraph(
                f"Budget vs. Camelot Portfolio Comparables — Cost-Beat Analysis · "
                f"{date.today().strftime('%B %d, %Y')}", st["subtitle"])],
        ],
        colWidths=[10.0 * inch],
    )
    band.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("LINEBELOW", (0, -1), (-1, -1), 2.5, GOLD),
    ]))
    return band


def _section_head(title: str, st: dict) -> list[Any]:
    return [Paragraph(title.upper(), st["section"]),
            HRFlowable(width="100%", thickness=1.2, color=GOLD, spaceAfter=6)]


def _cost_beat_table(analysis: CostBeatAnalysis, st: dict) -> Table:
    """The six-column comparison table, addressed lines first."""
    rows: list[list[Any]] = [[
        Paragraph("Line Item", st["th"]),
        Paragraph("Their Budget", st["th_r"]),
        Paragraph("Camelot Comparable Evidence", st["th"]),
        Paragraph("Camelot Target (Est.)", st["th_r"]),
        Paragraph("Est. Annual Savings", st["th_r"]),
        Paragraph("%", st["th_r"]),
        Paragraph("How We Get There", st["th"]),
    ]]

    ordered = (
        [ln for ln in analysis.addressed_lines if not ln.at_market]
        + [ln for ln in analysis.addressed_lines if ln.at_market]
        + analysis.not_addressed_lines
    )

    at_market_rows: list[int] = []
    not_addressed_rows: list[int] = []

    for line in ordered:
        index = len(rows)
        if not line.addressed:
            not_addressed_rows.append(index)
        elif line.at_market:
            at_market_rows.append(index)

        label = line.label
        if line.scope_protected:
            label += " *"
        savings = f"${line.savings:,.0f}" if line.savings > 0 else "—"
        pct = f"{line.savings_pct * 100:.0f}%" if line.savings > 0 else "0%"

        rows.append([
            Paragraph(label, st["td_b"]),
            Paragraph(f"${line.current_budget:,.0f}", st["td_r"]),
            Paragraph(line.evidence, st["td"]),
            Paragraph(f"${line.target:,.0f}", st["td_r"]),
            Paragraph(savings, st["td_rb"] if line.savings > 0 else st["td_r"]),
            Paragraph(pct, st["td_r"]),
            Paragraph(line.recommendation, st["td"]),
        ])

    rows.append([
        Paragraph("TOTAL", st["td_b"]),
        Paragraph(f"${analysis.total_budget:,.0f}", st["td_rb"]),
        Paragraph(
            f"{analysis.benchmark_coverage} categor"
            f"{'y' if analysis.benchmark_coverage == 1 else 'ies'} with Camelot comparables",
            st["td"]),
        Paragraph(f"${analysis.total_target:,.0f}", st["td_rb"]),
        Paragraph(f"${analysis.total_savings:,.0f}", st["td_rb"]),
        Paragraph(f"{analysis.savings_pct * 100:.1f}%", st["td_rb"]),
        Paragraph("Addressable savings as a share of the total budget.", st["td"]),
    ])

    table = Table(
        rows,
        colWidths=[w * inch for w in (1.45, 0.75, 2.5, 0.8, 0.8, 0.35, 3.35)],
        repeatRows=1,
    )

    style = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("LINEBELOW", (0, 0), (-1, 0), 2, GOLD),
        ("GRID", (0, 0), (-1, -1), 0.4, MID_GREY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("BACKGROUND", (0, -1), (-1, -1), LIGHT_GOLD),
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, GOLD),
    ]
    for index in at_market_rows:
        style.append(("BACKGROUND", (0, index), (-1, index), LIGHT_GREY))
    for index in not_addressed_rows:
        style.append(("BACKGROUND", (0, index), (-1, index), colors.HexColor("#FAF6EC")))
        style.append(("TEXTCOLOR", (0, index), (-1, index), DARK_GREY))

    table.setStyle(TableStyle(style))
    return table


def _totals_note(analysis: CostBeatAnalysis, st: dict) -> Paragraph:
    at_market_count = sum(1 for ln in analysis.addressed_lines if ln.at_market)
    text = (
        f"Addressable savings total <b>${analysis.total_savings:,.0f}</b> against a "
        f"<b>${analysis.total_budget:,.0f}</b> operating budget — "
        f"<b>{analysis.savings_pct * 100:.1f}%</b> of total spend. "
    )
    if analysis.unit_count:
        text += f"That is ${analysis.total_savings / analysis.unit_count:,.0f} per unit per year. "
    if at_market_count:
        text += (
            f"{at_market_count} line{'s' if at_market_count != 1 else ''} came back at "
            f"market against the comparables and carry no recommended change."
        )
    return Paragraph(text, st["body"])


def _not_addressed_note(analysis: CostBeatAnalysis, st: dict) -> Paragraph:
    not_addressed = analysis.not_addressed_lines
    if not not_addressed:
        return Paragraph(
            "Every expense line in the budget mapped to a Camelot expense category "
            "with at least one comparable building on file.", st["body"])

    names = ", ".join(ln.label for ln in not_addressed)
    return Paragraph(
        f"<b>Not addressed:</b> ${analysis.not_addressed_total:,.0f} of budgeted spend "
        f"across {len(not_addressed)} line{'s' if len(not_addressed) != 1 else ''} "
        f"({names}) has no comparable Camelot building on file at this size. Those "
        f"lines are excluded from the savings total and need a records and "
        f"vendor-bid review before any target can be set.", st["body"])


def _fee_proposal(proposal: FeeProposal, st: dict) -> Table:
    """Both options side by side, recommended one on a gold ground."""

    def column(option, label: str) -> list[Any]:
        recommended = option.model == proposal.recommended_model
        heading = f"{label}{'  ·  RECOMMENDED' if recommended else ''}"
        cells: list[Any] = [
            Paragraph(heading, st["opt_head"]),
            Paragraph(option.headline, st["opt_body"]),
            Spacer(1, 3),
        ]
        cells.extend(Paragraph(f"• {point}", st["opt_body"]) for point in option.talking_points)
        return cells

    table = Table(
        [[
            column(proposal.one_time, f"Option A — One-Time Cost-Recovery Fee "
                                      f"({proposal.one_time.camelot_share_pct * 100:.0f}% of Year-1 savings)"),
            column(proposal.uplift, f"Option B — Management-Fee Uplift "
                                    f"({proposal.uplift.camelot_share_pct * 100:.0f}% of annual savings)"),
        ]],
        colWidths=[4.9 * inch, 4.9 * inch],
    )

    recommended_col = 0 if proposal.recommended_model == ONE_TIME else 1
    other_col = 1 - recommended_col
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (recommended_col, 0), (recommended_col, 0), LIGHT_GOLD),
        ("BACKGROUND", (other_col, 0), (other_col, 0), LIGHT_GREY),
        ("BOX", (recommended_col, 0), (recommended_col, 0), 1.5, GOLD),
        ("BOX", (other_col, 0), (other_col, 0), 0.5, MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    return table


def next_steps(analysis: CostBeatAnalysis, proposal: FeeProposal) -> list[str]:
    """
    Build the follow-up checklist from what the analysis actually found, so each
    item names a specific action on a specific line.
    """
    per_category = {
        "hvac_mechanical": "Request three vendor bids for the HVAC service contract at current scope",
        "insurance": "Pull five years of insurance loss runs and issue a remarketing request to three carriers",
        "water_sewer": "Schedule a DEP water audit and a meter accuracy test",
        "electricity": "Request a utility tariff-class review and one fixed-rate supply quote",
        "gas": "Request supply-contract quotes and the boiler's most recent combustion test report",
        "payroll_and_cleaning": "Reconcile twelve months of payroll and porter hours against hours billed",
        "compactor_waste": "Log four weeks of actual container volume, then re-bid the carting contract",
        "exterminator": "Request a fixed monthly route quote from the vendor servicing nearby Camelot buildings",
        "elevator_maintenance": "Request a like-for-like elevator maintenance rebid; confirm no auto-renewal escalator",
        "sprinkler_fire_alarm": "Request a like-for-like inspection and monitoring rebid at code-required frequency",
        "phone_internet_cable": "Inventory every active circuit and cancel lines with no device attached",
        "intercom_security": "Request a like-for-like monitoring rebid and confirm no duplicate legacy line",
        "misc_repairs": "Pull twelve months of repair invoices and separate repairs from deferred capital work",
        "admin_fees": "Reconcile administrative spend to invoices and cancel unused subscription seats",
        "legal_accounting_management": "Request revised engagement letters with fixed fees for recurring matters",
        "taxes_bank_fees": "Verify assessed value and exemption status against the tax record",
    }

    steps = [
        per_category[line.category]
        for line in sorted(analysis.addressed_lines, key=lambda ln: ln.savings, reverse=True)
        if line.savings > 0 and line.category in per_category
    ]

    if analysis.not_addressed_lines:
        steps.append(
            "Pull vendor contracts and invoices for the not-addressed lines so a "
            "target can be set on them"
        )
    if analysis.needs_review:
        steps.append("Confirm the parsed budget figures against the source file before presenting")

    fee_label = ("the one-time cost-recovery fee" if proposal.recommended_model == ONE_TIME
                 else "the management-fee uplift")
    steps.append(f"Present the analysis to the board or owner with {fee_label} as the recommended structure")
    steps.append("Confirm the implementation sequence and the date the savings are measured from")
    return steps


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_report(
    analysis: CostBeatAnalysis,
    proposal: FeeProposal,
    output_dir: str,
    analysis_id: Optional[str] = None,
) -> str:
    """
    Render the cost-beat PDF and return its path.

    Landscape letter — the seven-column comparison table needs the width.
    """
    os.makedirs(output_dir, exist_ok=True)
    slug = "".join(c if c.isalnum() else "_" for c in analysis.property_name).strip("_").lower() or "building"
    suffix = (analysis_id or date.today().isoformat())[:8]
    output_path = os.path.join(output_dir, f"costbeat_{slug}_{suffix}.pdf")

    st = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(letter),
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.75 * inch,
        title=f"Camelot Cost-Beat Analysis — {analysis.property_name}",
        author="Camelot Property Management Services Corp",
    )

    story: list[Any] = [_header_band(analysis, st), Spacer(1, 0.16 * inch)]

    story.extend(_section_head("1. Budget vs. Camelot Portfolio Comparables", st))
    story.append(_cost_beat_table(analysis, st))
    story.append(Spacer(1, 0.12 * inch))

    story.extend(_section_head("2. Totals", st))
    story.append(_totals_note(analysis, st))

    story.extend(_section_head("3. Coverage Disclosure", st))
    story.append(_not_addressed_note(analysis, st))
    for warning in analysis.parse_warnings:
        story.append(Paragraph(f"<b>Parse note:</b> {warning}", st["body"]))

    story.extend(_section_head("4. Savings-Capture Fee Proposal", st))
    story.append(Paragraph(proposal.rationale, st["body"]))
    story.append(Spacer(1, 0.06 * inch))
    story.append(_fee_proposal(proposal, st))

    story.extend(_section_head("5. Follow-Up / Next Steps", st))
    story.extend(
        Paragraph(f"☐  {step}", st["check"]) for step in next_steps(analysis, proposal)
    )

    story.append(Spacer(1, 0.16 * inch))
    story.append(KeepTogether([
        HRFlowable(width="100%", thickness=1, color=MID_GREY, spaceAfter=5),
        Paragraph(
            "<b>Legend:</b>  * = fire/life-safety, elevator safety, or statutory scope — "
            f"rebid at identical scope only, never reduced.  &nbsp;|&nbsp;  "
            f"\"{AT_MARKET_TEXT}\" = within "
            f"{_at_market_threshold_pct():.0f}% of the comparable benchmark.  "
            f"&nbsp;|&nbsp;  Shaded rows carry no savings claim.",
            st["caveat"]),
        Spacer(1, 4),
        Paragraph(CAVEAT, st["caveat"]),
    ]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)

    with open(output_path, "wb") as f:
        f.write(buf.getvalue())

    logger.info("Cost-beat PDF written to %s", output_path)
    return output_path


def _at_market_threshold_pct() -> float:
    return float(load_config()["analysis"]["at_market_threshold_pct"]) * 100
