"""
report_generator.py — Perseus branded PDF
=========================================
Renders one period's variance analysis and its standalone fee proposal as a
Camelot-branded PDF, using the same visual system as `report_bot` and CostBeat —
dark navy #1A2645 bands, Camelot gold #C9A84C accents, Helvetica, and a
"Generated by Camelot OS · Perseus" footer.

Sections, in order:
  1. Header — property, address, period
  2. Where the period landed — the plain-language read
  3. Budget vs. Actual — Line Item | Budget Share | Actual | Variance | % | Status
  4. Portfolio comparison — Line Item | Annualized | Portfolio Avg | Target |
     Savings | % | How We Get There
  5. Addressable savings total and coverage disclosure
  6. Fee proposal for this period only — both options, recommended one highlighted
  7. Follow-up checklist
  8. Legend and caveat footer

Copy follows Camelot's house voice: a number never leads a sentence on its own —
it is stated with what it means; one statistic per sentence; no hedging and no
sales adjectives.

Author: Camelot OS
"""

from __future__ import annotations

import io
import logging
import os
from datetime import date
from typing import Any, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from perseus_bot.config_loader import load_config
from perseus_bot.fee_engine import ONE_TIME, FeeProposal
from perseus_bot.variance_engine import (
    FLAG_INVESTIGATE,
    FLAG_NO_BASELINE,
    FLAG_ON_TRACK,
    FLAG_UNDERSPENT,
    VarianceAnalysis,
    VarianceLine,
)

logger = logging.getLogger("perseus_bot.report_generator")

# ── Brand palette (matches report_bot/investor_update.py) ──────────────────
GOLD = colors.HexColor("#C9A84C")
NAVY = colors.HexColor("#1A2645")
LIGHT_GOLD = colors.HexColor("#F5EDD6")
LIGHT_GREY = colors.HexColor("#F5F5F5")
MID_GREY = colors.HexColor("#CCCCCC")
DARK_GREY = colors.HexColor("#555555")
RED = colors.HexColor("#B03A2E")
GREEN = colors.HexColor("#2E7D32")
WHITE = colors.white

STATUS_TEXT = {
    FLAG_INVESTIGATE: "Investigate",
    FLAG_UNDERSPENT: "Underspent",
    FLAG_ON_TRACK: "On track",
    FLAG_NO_BASELINE: "No budget line",
}

CAVEAT = (
    "Targets are good-faith estimates, not quotes; final numbers follow vendor bids "
    "and records review. Comparable costs are drawn from Camelot's own managed "
    "portfolio as reported in the monthly management reports for the periods cited. "
    "The budget share shown for each line is the annual budget divided evenly across "
    "the periods in the year unless the uploaded report supplied its own period "
    "budget. A line flagged Investigate is a question for the property manager, not a "
    "savings claim. Fire and life-safety, elevator safety, and statutory scope are "
    "never reduced — those lines may only be rebid at identical scope or audited for "
    "billing accuracy. The fee proposal covers this period's findings only and is not "
    "cumulative with any prior period or with a CostBeat annual-budget proposal."
)


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

def _styles() -> dict[str, ParagraphStyle]:
    return {
        "title": ParagraphStyle("pTitle", fontName="Helvetica-Bold", fontSize=17,
                                textColor=WHITE, alignment=TA_CENTER, spaceAfter=3),
        "subtitle": ParagraphStyle("pSubtitle", fontName="Helvetica", fontSize=10,
                                   textColor=LIGHT_GOLD, alignment=TA_CENTER),
        "section": ParagraphStyle("pSection", fontName="Helvetica-Bold", fontSize=12,
                                  textColor=NAVY, spaceBefore=12, spaceAfter=4),
        "body": ParagraphStyle("pBody", fontName="Helvetica", fontSize=9,
                               textColor=colors.black, leading=13, spaceAfter=5),
        "th": ParagraphStyle("pTh", fontName="Helvetica-Bold", fontSize=8, textColor=WHITE),
        "th_r": ParagraphStyle("pThR", fontName="Helvetica-Bold", fontSize=8,
                               textColor=WHITE, alignment=TA_RIGHT),
        "td": ParagraphStyle("pTd", fontName="Helvetica", fontSize=7.5, leading=9.5),
        "td_b": ParagraphStyle("pTdB", fontName="Helvetica-Bold", fontSize=7.5, leading=9.5),
        "td_r": ParagraphStyle("pTdR", fontName="Helvetica", fontSize=7.5,
                               leading=9.5, alignment=TA_RIGHT),
        "td_rb": ParagraphStyle("pTdRB", fontName="Helvetica-Bold", fontSize=7.5,
                                leading=9.5, alignment=TA_RIGHT),
        "opt_head": ParagraphStyle("pOptHead", fontName="Helvetica-Bold", fontSize=10,
                                   textColor=NAVY, spaceAfter=4),
        "opt_body": ParagraphStyle("pOptBody", fontName="Helvetica", fontSize=8,
                                   leading=11.5, spaceAfter=3),
        "check": ParagraphStyle("pCheck", fontName="Helvetica", fontSize=8.5,
                                leading=13, leftIndent=10, spaceAfter=2),
        "caveat": ParagraphStyle("pCaveat", fontName="Helvetica", fontSize=6.5,
                                 textColor=DARK_GREY, leading=9, alignment=TA_LEFT),
    }


def _footer(canvas: Any, doc: Any) -> None:
    """Gold rule plus the Camelot OS attribution line on every page."""
    canvas.saveState()
    width, _ = doc.pagesize
    y = 0.45 * inch
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(1)
    canvas.line(0.5 * inch, y + 12, width - 0.5 * inch, y + 12)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.grey)
    canvas.drawString(
        0.5 * inch, y,
        f"Generated by Camelot OS · Perseus | {date.today().strftime('%B %d, %Y')}",
    )
    canvas.drawRightString(width - 0.5 * inch, y, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _header_band(analysis: VarianceAnalysis, st: dict) -> Table:
    units = f"{analysis.unit_count} units" if analysis.unit_count else "unit count not supplied"
    detail = " · ".join(
        p for p in (analysis.address, units, analysis.building_type, analysis.market) if p
    )

    band = Table(
        [
            [Paragraph("CAMELOT PROPERTY MANAGEMENT SERVICES CORP", st["subtitle"])],
            [Paragraph(analysis.property_name.upper(), st["title"])],
            [Paragraph(detail, st["subtitle"])],
            [Paragraph(
                f"{analysis.period_label} Variance &amp; Savings Report · "
                f"{date.today().strftime('%B %d, %Y')}", st["subtitle"])],
        ],
        colWidths=[10.0 * inch],
    )
    band.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("LINEBELOW", (0, -1), (-1, -1), 2.5, GOLD),
    ]))
    return band


def _section_head(title: str, st: dict) -> list[Any]:
    return [Paragraph(title.upper(), st["section"]),
            HRFlowable(width="100%", thickness=1.2, color=GOLD, spaceAfter=6)]


def summary_paragraphs(analysis: VarianceAnalysis, proposal: FeeProposal) -> list[str]:
    """
    The plain-language read on the period. Each sentence carries one figure, and
    each figure arrives with what it means rather than on its own.
    """
    variance = analysis.budget_variance
    direction = "over" if variance > 0 else "under"
    paragraphs: list[str] = []

    if analysis.total_budget_period:
        paragraphs.append(
            f"The building ran <b>{direction} its budget share for "
            f"{analysis.period_label} by ${abs(variance):,.0f}</b>, on a prorated "
            f"share of ${analysis.total_budget_period:,.0f} "
            f"({abs(analysis.budget_variance_pct) * 100:.1f}% {direction}). "
            f"{_baseline_sentence(analysis)}"
        )
    else:
        paragraphs.append(
            f"No budget line matched the categories in this report, so "
            f"{analysis.period_label} is reported against the portfolio only. "
            f"{_baseline_sentence(analysis)}"
        )

    flagged = analysis.flagged_lines
    if flagged:
        names = _join_labels([ln.label for ln in flagged])
        paragraphs.append(
            f"<b>{len(flagged)} line{'s' if len(flagged) != 1 else ''} came in far "
            f"enough over budget to warrant a question</b> — {names}. Each one needs "
            f"its invoices pulled before the variance is treated as a price problem "
            f"rather than a timing one."
        )
    elif analysis.total_budget_period:
        paragraphs.append(
            "No category ran far enough over its budget share to warrant a question "
            "this period."
        )

    if analysis.portfolio_savings_annual > 0:
        paragraphs.append(
            f"Set against what Camelot pays across comparable buildings, this "
            f"period's run-rate is <b>${analysis.portfolio_savings_annual:,.0f} a year "
            f"above the portfolio</b> on the lines with comparable evidence — "
            f"${analysis.portfolio_savings_period:,.0f} of that falls in "
            f"{analysis.period_label} itself. That gap is addressable, and the "
            f"mechanism for each line is named in the table below."
        )
    elif analysis.benchmark_coverage:
        paragraphs.append(
            "Every category with comparable evidence sits at or below the portfolio "
            "average, so there is no addressable gap to price this period."
        )
    else:
        paragraphs.append(
            "No comparable Camelot building of this size is on file yet, so the "
            "portfolio check could not run. Seed portfolio_benchmarks from the "
            "monthly management reports and this half of the report fills in."
        )

    if analysis.seasonal_categories:
        paragraphs.append(
            f"<b>Seasonality caveat:</b> {_join_labels(analysis.seasonal_categories)} "
            f"do not arrive in even periods. Their budget share here is a flat split, "
            f"so read a variance on those lines against the same period last year "
            f"before acting on it."
        )

    return paragraphs


def _baseline_sentence(analysis: VarianceAnalysis) -> str:
    return analysis.baseline.describe() if analysis.baseline else ""


def _variance_table(analysis: VarianceAnalysis, st: dict) -> Table:
    """Budget vs. actual for the period, worst overrun first."""
    rows: list[list[Any]] = [[
        Paragraph("Line Item", st["th"]),
        Paragraph("Budget Share", st["th_r"]),
        Paragraph(f"{analysis.period_label} Actual", st["th_r"]),
        Paragraph("Variance", st["th_r"]),
        Paragraph("%", st["th_r"]),
        Paragraph("Status", st["th"]),
        Paragraph("What Drives It / What To Check", st["th"]),
    ]]

    ordered = sorted(
        analysis.lines,
        key=lambda ln: (ln.budget_period is None, -ln.budget_variance),
    )

    flag_rows: list[int] = []
    quiet_rows: list[int] = []

    for line in ordered:
        index = len(rows)
        if line.budget_flag == FLAG_INVESTIGATE:
            flag_rows.append(index)
        elif line.budget_flag == FLAG_NO_BASELINE:
            quiet_rows.append(index)

        label = line.label + (" *" if line.scope_protected else "") + ("  †" if line.seasonal else "")
        if line.budget_period is None:
            budget_cell, variance_cell, pct_cell = "—", "—", "—"
        else:
            budget_cell = f"${line.budget_period:,.0f}"
            variance_cell = (
                f"+${line.budget_variance:,.0f}" if line.budget_variance >= 0
                else f"(${abs(line.budget_variance):,.0f})"
            )
            pct_cell = f"{line.budget_variance_pct * 100:+.0f}%"

        rows.append([
            Paragraph(label, st["td_b"]),
            Paragraph(budget_cell, st["td_r"]),
            Paragraph(f"${line.actual_period:,.0f}", st["td_r"]),
            Paragraph(variance_cell, st["td_rb"] if line.flagged else st["td_r"]),
            Paragraph(pct_cell, st["td_r"]),
            Paragraph(STATUS_TEXT.get(line.budget_flag, line.budget_flag), st["td"]),
            Paragraph(_variance_note(line), st["td"]),
        ])

    total_variance = analysis.budget_variance
    rows.append([
        Paragraph("TOTAL", st["td_b"]),
        Paragraph(f"${analysis.total_budget_period:,.0f}", st["td_rb"]),
        Paragraph(f"${analysis.total_actual_budgeted_period:,.0f}", st["td_rb"]),
        Paragraph(
            f"+${total_variance:,.0f}" if total_variance >= 0
            else f"(${abs(total_variance):,.0f})", st["td_rb"]),
        Paragraph(f"{analysis.budget_variance_pct * 100:+.1f}%", st["td_rb"]),
        Paragraph(
            f"{len(analysis.flagged_lines)} flagged", st["td_b"]),
        Paragraph(_totals_basis_note(analysis), st["td"]),
    ])

    table = Table(
        rows,
        colWidths=[w * inch for w in (1.6, 0.85, 0.9, 0.85, 0.5, 0.75, 4.55)],
        repeatRows=1,
    )
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("LINEBELOW", (0, 0), (-1, 0), 2, GOLD),
        ("GRID", (0, 0), (-1, -1), 0.4, MID_GREY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("BACKGROUND", (0, -1), (-1, -1), LIGHT_GOLD),
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, GOLD),
    ]
    for index in flag_rows:
        style.append(("BACKGROUND", (0, index), (-1, index), colors.HexColor("#FBEEEC")))
        style.append(("TEXTCOLOR", (5, index), (5, index), RED))
    for index in quiet_rows:
        style.append(("BACKGROUND", (0, index), (-1, index), LIGHT_GREY))
        style.append(("TEXTCOLOR", (0, index), (-1, index), DARK_GREY))
    table.setStyle(TableStyle(style))
    return table


def _totals_basis_note(analysis: VarianceAnalysis) -> str:
    """
    State what the totals row does and does not count.

    The row only totals the lines carrying a budget share, so when some lines
    have none the Actual column will not add up to this figure. Say so, and give
    the full period spend, rather than leaving the owner to find the gap.
    """
    budgeted = len(analysis.budgeted_lines)
    unbudgeted = len(analysis.lines) - budgeted
    if not unbudgeted:
        return "Totals cover every line on the report."
    subject = "line" if unbudgeted == 1 else "lines"
    verb = "is" if unbudgeted == 1 else "are"
    basis = "the one line" if budgeted == 1 else f"the {budgeted} lines"
    return (
        f"Totals cover {basis} with a budget share. {unbudgeted} {subject} without "
        f"one {verb} listed for completeness and excluded here; total spend for the "
        f"period was ${analysis.total_actual_period:,.0f}."
    )


def _variance_note(line: VarianceLine) -> str:
    """One sentence on what the variance means for this line."""
    if line.budget_flag == FLAG_NO_BASELINE:
        return (
            "No matching line in the budget baseline. Add it to the budget or "
            "confirm the spend belongs to another category."
        )
    if line.budget_flag == FLAG_INVESTIGATE:
        base = (
            f"Running ${line.budget_variance:,.0f} over the period share. "
            if line.budget_variance
            else ""
        )
        if line.seasonal:
            return base + (
                "This category is seasonal, so compare against the same period last "
                "year before treating the overrun as a price problem."
            )
        return base + "Pull the invoices behind the line for the period."
    if line.budget_flag == FLAG_UNDERSPENT:
        return (
            "Under the period share. Usually deferred work or a bill that has not "
            "landed yet — confirm which, so the year-end position is not a surprise."
        )
    return "Tracking within the budget share for the period."


def _portfolio_table(analysis: VarianceAnalysis, st: dict) -> Table:
    """Annualized run-rate against the portfolio average, largest gap first."""
    rows: list[list[Any]] = [[
        Paragraph("Line Item", st["th"]),
        Paragraph("Annualized Run-Rate", st["th_r"]),
        Paragraph("Camelot Comparable Evidence", st["th"]),
        Paragraph("Portfolio Target (Est.)", st["th_r"]),
        Paragraph("Est. Annual Savings", st["th_r"]),
        Paragraph("%", st["th_r"]),
        Paragraph("How We Get There", st["th"]),
    ]]

    ordered = (
        sorted(analysis.savings_lines, key=lambda ln: ln.portfolio_savings_annual, reverse=True)
        + [ln for ln in analysis.addressed_lines if ln.portfolio_savings_annual <= 0]
        + analysis.not_addressed_lines
    )

    at_average_rows: list[int] = []
    not_addressed_rows: list[int] = []

    for line in ordered:
        index = len(rows)
        if not line.addressed:
            not_addressed_rows.append(index)
        elif line.portfolio_savings_annual <= 0:
            at_average_rows.append(index)

        label = line.label + (" *" if line.scope_protected else "")
        savings = (
            f"${line.portfolio_savings_annual:,.0f}"
            if line.portfolio_savings_annual > 0 else "—"
        )
        pct = (
            f"{line.portfolio_savings_annual / line.annualized_actual * 100:.0f}%"
            if line.portfolio_savings_annual > 0 and line.annualized_actual else "0%"
        )

        rows.append([
            Paragraph(label, st["td_b"]),
            Paragraph(f"${line.annualized_actual:,.0f}", st["td_r"]),
            Paragraph(line.evidence, st["td"]),
            Paragraph(f"${line.portfolio_target_annual:,.0f}", st["td_r"]),
            Paragraph(savings, st["td_rb"] if line.portfolio_savings_annual > 0 else st["td_r"]),
            Paragraph(pct, st["td_r"]),
            Paragraph(line.recommendation, st["td"]),
        ])

    rows.append([
        Paragraph("TOTAL", st["td_b"]),
        Paragraph(f"${analysis.annualized_actual:,.0f}", st["td_rb"]),
        Paragraph(
            f"{analysis.benchmark_coverage} categor"
            f"{'y' if analysis.benchmark_coverage == 1 else 'ies'} with Camelot comparables",
            st["td"]),
        Paragraph(
            f"${analysis.annualized_actual - analysis.portfolio_savings_annual:,.0f}",
            st["td_rb"]),
        Paragraph(f"${analysis.portfolio_savings_annual:,.0f}", st["td_rb"]),
        Paragraph(f"{analysis.savings_pct_of_annualized * 100:.1f}%", st["td_rb"]),
        Paragraph(
            "Addressable savings as a share of the annualized run-rate.", st["td"]),
    ])

    table = Table(
        rows,
        colWidths=[w * inch for w in (1.45, 0.9, 2.4, 0.85, 0.85, 0.35, 3.2)],
        repeatRows=1,
    )
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("LINEBELOW", (0, 0), (-1, 0), 2, GOLD),
        ("GRID", (0, 0), (-1, -1), 0.4, MID_GREY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("BACKGROUND", (0, -1), (-1, -1), LIGHT_GOLD),
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, GOLD),
    ]
    for index in at_average_rows:
        style.append(("BACKGROUND", (0, index), (-1, index), LIGHT_GREY))
    for index in not_addressed_rows:
        style.append(("BACKGROUND", (0, index), (-1, index), colors.HexColor("#FAF6EC")))
        style.append(("TEXTCOLOR", (0, index), (-1, index), DARK_GREY))
    table.setStyle(TableStyle(style))
    return table


def _coverage_note(analysis: VarianceAnalysis, st: dict) -> list[Any]:
    """What the report could not reach, stated before anyone has to ask."""
    notes: list[Any] = []
    not_addressed = analysis.not_addressed_lines
    if not_addressed:
        total = sum(ln.annualized_actual for ln in not_addressed)
        names = _join_labels([ln.label for ln in not_addressed])
        notes.append(Paragraph(
            f"<b>Not addressed:</b> ${total:,.0f} of annualized spend across "
            f"{len(not_addressed)} line{'s' if len(not_addressed) != 1 else ''} "
            f"({names}) has no comparable Camelot building on file at this size. "
            f"Those lines are excluded from the savings total and need a records and "
            f"vendor-bid review before any target can be set.", st["body"]))
    else:
        notes.append(Paragraph(
            "Every expense line in the report mapped to a Camelot expense category "
            "with at least one comparable building on file.", st["body"]))

    for warning in analysis.parse_warnings:
        notes.append(Paragraph(f"<b>Parse note:</b> {warning}", st["body"]))
    if analysis.needs_review:
        notes.append(Paragraph(
            "<b>Review before sending:</b> the parsed figures could not be "
            "reconciled against a total stated in the source file. Confirm each line "
            "against the report before this goes to a client.", st["body"]))
    return notes


def _fee_proposal(proposal: FeeProposal, st: dict) -> Table:
    """Both options side by side, recommended one on a gold ground."""

    def column(option, label: str) -> list[Any]:
        recommended = option.model == proposal.recommended_model
        heading = f"{label}{'  ·  RECOMMENDED' if recommended else ''}"
        cells: list[Any] = [
            Paragraph(heading, st["opt_head"]),
            Paragraph(option.headline, st["opt_body"]),
            Spacer(1, 3),
        ]
        cells.extend(Paragraph(f"• {point}", st["opt_body"]) for point in option.talking_points)
        return cells

    table = Table(
        [[
            column(
                proposal.one_time,
                f"Option A — One-Time Fee "
                f"({proposal.one_time.camelot_share_pct * 100:.0f}% of "
                f"{proposal.period_label} savings)",
            ),
            column(
                proposal.uplift,
                f"Option B — Management-Fee Uplift "
                f"({proposal.uplift.camelot_share_pct * 100:.0f}% of annualized savings)",
            ),
        ]],
        colWidths=[4.9 * inch, 4.9 * inch],
    )

    recommended_col = 0 if proposal.recommended_model == ONE_TIME else 1
    other_col = 1 - recommended_col
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (recommended_col, 0), (recommended_col, 0), LIGHT_GOLD),
        ("BACKGROUND", (other_col, 0), (other_col, 0), LIGHT_GREY),
        ("BOX", (recommended_col, 0), (recommended_col, 0), 1.5, GOLD),
        ("BOX", (other_col, 0), (other_col, 0), 0.5, MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    return table


PER_CATEGORY_STEPS = {
    "hvac_mechanical": "Request three vendor bids for the HVAC service contract at current scope",
    "insurance": "Pull five years of insurance loss runs and issue a remarketing request to three carriers",
    "water_sewer": "Schedule a DEP water audit and a meter accuracy test",
    "electricity": "Request a utility tariff-class review and one fixed-rate supply quote",
    "gas": "Request supply-contract quotes and the boiler's most recent combustion test report",
    "payroll_and_cleaning": "Reconcile the period's payroll and porter hours against hours billed",
    "compactor_waste": "Log four weeks of actual container volume, then re-bid the carting contract",
    "exterminator": "Request a fixed monthly route quote from the vendor servicing nearby Camelot buildings",
    "elevator_maintenance": "Request a like-for-like elevator maintenance rebid; confirm no auto-renewal escalator",
    "sprinkler_fire_alarm": "Request a like-for-like inspection and monitoring rebid at code-required frequency",
    "phone_internet_cable": "Inventory every active circuit and cancel lines with no device attached",
    "intercom_security": "Request a like-for-like monitoring rebid and confirm no duplicate legacy line",
    "misc_repairs": "Pull the period's repair invoices and separate repairs from deferred capital work",
    "admin_fees": "Reconcile administrative spend to invoices and cancel unused subscription seats",
    "legal_accounting_management": "Request revised engagement letters with fixed fees for recurring matters",
    "taxes_bank_fees": "Verify assessed value and exemption status against the tax record",
}


def next_steps(analysis: VarianceAnalysis, proposal: FeeProposal) -> list[str]:
    """
    Build the follow-up checklist from what this period actually found, so each
    item names a specific action on a specific line.
    """
    steps: list[str] = []

    for line in sorted(analysis.flagged_lines, key=lambda ln: ln.budget_variance, reverse=True):
        steps.append(
            f"Pull the {analysis.period_label} invoices for {line.label} and confirm "
            f"whether the ${line.budget_variance:,.0f} overrun is timing, scope, or price"
        )

    for line in sorted(
        analysis.savings_lines, key=lambda ln: ln.portfolio_savings_annual, reverse=True
    ):
        step = PER_CATEGORY_STEPS.get(line.category)
        if step and step not in steps:
            steps.append(step)

    if analysis.not_addressed_lines:
        steps.append(
            "Pull vendor contracts and invoices for the not-addressed lines so a "
            "target can be set on them"
        )
    if not analysis.benchmark_coverage:
        steps.append(
            "Seed portfolio_benchmarks from the monthly management reports so the "
            "portfolio comparison can run next period"
        )
    if analysis.needs_review:
        steps.append(
            "Confirm the parsed figures against the source report before presenting"
        )

    fee_label = (
        f"the one-time fee on {analysis.period_label}'s findings"
        if proposal.recommended_model == ONE_TIME
        else "the management-fee uplift"
    )
    steps.append(
        f"Present the period to the board or owner with {fee_label} as the "
        f"recommended structure"
    )
    steps.append(
        "Confirm the implementation sequence and the date the savings are measured from"
    )
    return steps


def _join_labels(labels: list[str]) -> str:
    """Oxford-comma join, capped so the sentence stays readable."""
    unique = list(dict.fromkeys(labels))
    shown, remainder = unique[:4], len(unique) - 4
    if not shown:
        return "none"
    if len(shown) == 1:
        joined = shown[0]
    elif len(shown) == 2:
        joined = f"{shown[0]} and {shown[1]}"
    else:
        joined = ", ".join(shown[:-1]) + f", and {shown[-1]}"
    return f"{joined}, plus {remainder} more" if remainder > 0 else joined


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_report(
    analysis: VarianceAnalysis,
    proposal: FeeProposal,
    output_dir: str,
    report_id: Optional[str] = None,
) -> str:
    """
    Render the period variance PDF and return its path.

    Landscape letter — the seven-column comparison tables need the width.
    """
    os.makedirs(output_dir, exist_ok=True)
    slug = (
        "".join(c if c.isalnum() else "_" for c in analysis.property_name).strip("_").lower()
        or "building"
    )
    period_slug = (
        f"{analysis.year}_{analysis.quarter}".lower() if analysis.quarter else str(analysis.year)
    )
    suffix = (report_id or date.today().isoformat())[:8]
    output_path = os.path.join(output_dir, f"perseus_{slug}_{period_slug}_{suffix}.pdf")

    st = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(letter),
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.75 * inch,
        title=f"Camelot {analysis.period_label} Variance Report — {analysis.property_name}",
        author="Camelot Property Management Services Corp",
    )

    story: list[Any] = [_header_band(analysis, st), Spacer(1, 0.16 * inch)]

    story.extend(_section_head(f"1. Where {analysis.period_label} Landed", st))
    story.extend(Paragraph(text, st["body"]) for text in summary_paragraphs(analysis, proposal))

    story.extend(_section_head(f"2. Budget vs. Actual — {analysis.period_label}", st))
    story.append(_variance_table(analysis, st))

    story.extend(_section_head("3. Annualized Run-Rate vs. Camelot Portfolio Average", st))
    story.append(_portfolio_table(analysis, st))

    story.extend(_section_head("4. Coverage Disclosure", st))
    story.extend(_coverage_note(analysis, st))

    story.extend(_section_head(f"5. Fee Proposal — {analysis.period_label} Only", st))
    story.append(Paragraph(proposal.rationale, st["body"]))
    story.append(Paragraph(
        f"This proposal prices the savings identified in {analysis.period_label}. It "
        f"is not cumulative with a prior period and is not netted against any annual "
        f"budget proposal for the same building.", st["body"]))
    story.append(Spacer(1, 0.06 * inch))
    story.append(_fee_proposal(proposal, st))

    story.extend(_section_head("6. Follow-Up / Next Steps", st))
    story.extend(Paragraph(f"☐  {step}", st["check"]) for step in next_steps(analysis, proposal))

    story.append(Spacer(1, 0.16 * inch))
    story.append(KeepTogether([
        HRFlowable(width="100%", thickness=1, color=MID_GREY, spaceAfter=5),
        Paragraph(
            f"<b>Legend:</b>  * = fire/life-safety, elevator safety, or statutory "
            f"scope — rebid at identical scope only, never reduced.  &nbsp;|&nbsp;  "
            f"† = seasonal category, budget share is a flat split.  &nbsp;|&nbsp;  "
            f"\"Investigate\" = more than {_overrun_threshold_pct():.0f}% over the "
            f"period's budget share.  &nbsp;|&nbsp;  Shaded rows carry no savings "
            f"claim.", st["caveat"]),
        Spacer(1, 4),
        Paragraph(CAVEAT, st["caveat"]),
    ]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)

    with open(output_path, "wb") as f:
        f.write(buf.getvalue())

    logger.info("Perseus variance PDF written to %s", output_path)
    return output_path


def _overrun_threshold_pct() -> float:
    return float(load_config()["variance"]["budget_overrun_flag_pct"]) * 100
